### ISSUE TITLE
US Output format issue

### ISSUE THREAD

**Issue by JackieDreamy** [JackieDreamy/AgileSprint#41]
All of your error messages are too vague. You should refer to the specific individual whose birth or marriage, etc. is in error. Also, a generic reference like "Dates(birth, marriage, divorce, death) of family" is too vague. Which date?

**Comment by JackieDreamy** [comment]
Referenced Update

**Comment by JackieDreamy** [comment]
Fix 02,05,09,16
[ERROR] CODE US02: 
CATEGORY: PERSON
REASON: Birth of member [FamilyId: @F9@ PersonId: @P15@ Name: Darlene/Cook/ BirthDate: Sun Oct 18 00:00:00 EDT 1998] date should occur before marriage date [Wed Jun 10 00:00:00 EDT 1953] of an individual

[ERROR] CODE US05: 
CATEGORY: PERSON
REASON: Family [@F10@] marriage date [Thu Nov 06 00:00:00 EST 1997] should occur before death of either spouse [PersonId: @P28@ Name: KennethArvid/Lindfors/ DeathDate: Sun Dec 10 00:00:00 EST 1995]

[ERROR] CODE US09: 
CATEGORY: PERSON
REASON: Child [PersonId: @P16@, Name: Inez/Youngster/ BirthDate: Thu Jun 04 00:00:00 EDT 1970] from family [@F5@] should be born before death of mother and before 9 months after death of father [@P9@'s deathDate: Thu Apr 11 00:00:00 EST 1963]

[ERROR] CODE US16: 
CATEGORY: PERSON
REASON: Male members [PersonId: @P19@, Name: John/Elsaesser/] of a family [@F12@] have not the same last name [Jakob/Elsasser/]

**Comment by evelinezhang** [comment]
Fixed bug #44 : output format issue for US04,06 
Done:
1. Updated output format to US04, US06 according to professor's comments.
a. removed us04ParseCondition function from DateUtils.java
b. updated parseUS04Error, parseUS06Error in DateUtils.java
c. updated US04_PERSON, US06_PERSON in ErrorInfo.java

2. Added Unit test cases for US04, US06

**Comment by evelinezhang** [comment]
Fixed bug #44 output format issue for US04,06
[ERROR] CODE US04: 
CATEGORY: PERSON
REASON: Divorce date [Tue Mar 15 00:00:00 EST 1921] occurs before marriage date [Tue Jun 20 00:00:00 EDT 1922] in Family [@F8@]

[ERROR] CODE US06: 
CATEGORY: PERSON
REASON: Individual [PersonId: @P28@, Name: KennethArvid/Lindfors/, BirthDate: Mon May 20 00:00:00 EDT 1935]'s death date [Sun Dec 10 00:00:00 EST 1995] occurs before divorce date [Wed May 09 00:00:00 EDT 2001] in Family [@F10@]
